print('Welcome to the Band Name generator')
city_name = input("What's the name of the city you grew in? \n")
pet_name = input("What's your pet's name \n")
band_name = city_name.title() + ' ' + pet_name.title()
print(f'Your Band name could be {band_name}')